apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthenticationConfiguration
jwt:
- issuer:
    url: https://localhost:32000
    audiences:
    - kubernetes
    certificateAuthority: |
      -----BEGIN CERTIFICATE-----
      MIIDBTCCAe2gAwIBAgIUIX5Tpx94kKtQbByo51/Hf4hnzuUwDQYJKoZIhvcNAQEL
      BQAwEjEQMA4GA1UEAwwHa3ViZS1jYTAeFw0yNTAzMDEwNTEyNDJaFw0zNTAyMjcw
      NTEyNDJaMBIxEDAOBgNVBAMMB2t1YmUtY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IB
      DwAwggEKAoIBAQC1V6XOyXRqTRtzwBuKbCbsWP+mSLkXD0qsvef002Ew9FWawD2K
      YzulM0tF0Wbqq2C8xq580/YF/bVxX5X6SnPszSysuYIhU5TW/TRCO/cVlXf+L7tq
      Mo2CzjEGWYh429OqHX+yUWO7uer9qW90VvMh1FA52jES3yAR+WHlng8WNyfbClsb
      otWi/7eNk/9ezRdr8h5okH80xEh0WEsLW/4Bb2+vtdmmkBj3sumiZtflqkkOZuJY
      ZR8CoswIzMeT27MiI4U8XAbEHo3fvtcBPs0vMlN4HiZed3gVttAh1dxrdNcwY+NG
      ly8mamP4MA9rgeOr/tz2uZ4brJBng1V3HQNDAgMBAAGjUzBRMB0GA1UdDgQWBBS0
      ccWkuhrFSGRq2EnaCWL4/AhBDDAfBgNVHSMEGDAWgBS0ccWkuhrFSGRq2EnaCWL4
      /AhBDDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCtU+byOx2y
      PHZMYhKvJ8J6T/8FTinpoag4/btAxZheWykwlFVoRrcngEcNcoMoBr3Wpbnnop2k
      gjHR5ODL/ZaBFxzk+tJ6OA/70X8p7FLvVTI9pdIXMAmOLDgYzDJMeVyc8uXasaOF
      DqKGwIyh/kEziDUFdngDbzz8l6g5QwHjxBmQ0vJkqt2S4Ts1o9U/DPFlx2JuqAme
      E6VJjgH2Rg+2fsvypOElMLqNBG0n5G1eT+m/eCfGZ7f5K0jrM0gXkX4tl0QR7W4e
      UmdmCejsMxHBISZJVcMILmfJ/CO4qAmzmuQHtITvk28IjqpEQ3O+rm2hEMNbs9yV
      owvADt5bXYeX
      -----END CERTIFICATE-----
  claimMappings:
    username:
      prefix: ""
      claim: email
    groups:
      prefix: ""
      claim: groups
  userValidationRules:
  - expression: "!user.username.startsWith('system:')"
    message: "username cannot use reserved system: prefix"
